export function FirebaseAuthError(error: any): string {
  const errorMessages: { [key: string]: string } = {
    'auth/admin-restricted-operation': 'This operation is restricted to administrators.',
    'auth/argument-error': 'Invalid argument provided.',
    'auth/app-not-authorized': 'This app is not authorized to use Firebase Authentication.',
    'auth/app-not-installed': 'The app is not installed.',
    'auth/captcha-check-failed': 'Captcha verification failed. Please try again.',
    'auth/code-expired': 'The code has expired. Please request a new one.',
    'auth/cordova-not-ready': 'The Cordova app is not ready.',
    'auth/cors-unsupported': 'Your browser does not support CORS.',
    'auth/credential-already-in-use': 'This credential is already associated with an account.',
    'auth/custom-token-mismatch': 'The custom token provided is incorrect.',
    'auth/requires-recent-login': 'Please log in again to continue.',
    'auth/dependent-sdk-initialized-before-auth': 'A dependent SDK was initialized before authentication.',
    'auth/dynamic-link-not-activated': 'Dynamic link functionality is not enabled.',
    'auth/email-already-in-use': 'The email address is already in use.',
    'auth/emulator-config-failed': 'Emulator configuration failed.',
    'auth/expired-action-code': 'The action code has expired.',
    'auth/cancelled-popup-request': 'The popup request was canceled.',
    'auth/internal-error': 'An internal error occurred. Please try again later.',
    'auth/invalid-api-key': 'Invalid API key.',
    'auth/invalid-app-credential': 'Invalid app credential.',
    'auth/invalid-app-id': 'Invalid app ID.',
    'auth/invalid-user-token': 'Invalid user token. Please sign in again.',
    'auth/invalid-auth-event': 'Invalid authentication event.',
    'auth/invalid-cert-hash': 'Invalid certificate hash.',
    'auth/invalid-verification-code': 'The verification code is invalid.',
    'auth/invalid-continue-uri': 'The continue URL is invalid.',
    'auth/invalid-cordova-configuration': 'Invalid Cordova configuration.',
    'auth/invalid-custom-token': 'The custom token provided is invalid.',
    'auth/invalid-dynamic-link-domain': 'Invalid dynamic link domain.',
    'auth/invalid-email': 'The email address is badly formatted.',
    'auth/invalid-emulator-scheme': 'Invalid emulator scheme.',
    'auth/invalid-credential': 'Invalid login credentials. Please try again.',
    'auth/invalid-message-payload': 'Invalid message payload.',
    'auth/invalid-multi-factor-session': 'Invalid multi-factor session.',
    'auth/invalid-oauth-client-id': 'Invalid OAuth client ID.',
    'auth/invalid-oauth-provider': 'Invalid OAuth provider.',
    'auth/invalid-action-code': 'Invalid action code.',
    'auth/unauthorized-domain': 'Unauthorized domain.',
    'auth/wrong-password': 'Incorrect email or password.',
    'auth/invalid-persistence-type': 'Invalid persistence type.',
    'auth/invalid-phone-number': 'The phone number is not in a valid format.',
    'auth/invalid-provider-id': 'Invalid provider ID.',
    'auth/invalid-recipient-email': 'Invalid recipient email.',
    'auth/invalid-sender': 'Invalid sender.',
    'auth/invalid-verification-id': 'The verification ID is invalid.',
    'auth/invalid-tenant-id': 'Invalid tenant ID.',
    'auth/multi-factor-info-not-found': 'Multi-factor information not found.',
    'auth/multi-factor-auth-required': 'Multi-factor authentication is required.',
    'auth/missing-android-pkg-name': 'Android package name is required.',
    'auth/missing-app-credential': 'App credential is missing.',
    'auth/auth-domain-config-required': 'Authentication domain configuration is required.',
    'auth/missing-verification-code': 'Verification code is missing.',
    'auth/missing-continue-uri': 'Continue URL is missing.',
    'auth/missing-iframe-start': 'Missing iframe start.',
    'auth/missing-ios-bundle-id': 'iOS bundle ID is required.',
    'auth/missing-or-invalid-nonce': 'Nonce is missing or invalid.',
    'auth/missing-multi-factor-info': 'Multi-factor information is missing.',
    'auth/missing-multi-factor-session': 'Multi-factor session is missing.',
    'auth/missing-phone-number': 'Phone number is required.',
    'auth/missing-verification-id': 'Verification ID is missing.',
    'auth/app-deleted': 'The app has been deleted.',
    'auth/account-exists-with-different-credential': 'An account already exists with a different credential.',
    'auth/network-request-failed': 'Network error. Please check your internet connection.',
    'auth/null-user': 'No user is signed in.',
    'auth/no-auth-event': 'No authentication event found.',
    'auth/no-such-provider': 'No such provider.',
    'auth/operation-not-allowed': 'This operation is not allowed. Please contact support.',
    'auth/operation-not-supported-in-this-environment': 'This operation is not supported in this environment.',
    'auth/popup-blocked': 'Popup was blocked by the browser.',
    'auth/popup-closed-by-user': 'The popup was closed by the user.',
    'auth/provider-already-linked': 'This provider is already linked to the account.',
    'auth/quota-exceeded': 'Quota exceeded. Please try again later.',
    'auth/redirect-cancelled-by-user': 'The redirect was canceled by the user.',
    'auth/redirect-operation-pending': 'A redirect operation is pending.',
    'auth/rejected-credential': 'The credential was rejected.',
    'auth/second-factor-already-in-use': 'The second factor is already in use.',
    'auth/maximum-second-factor-count-exceeded': 'Maximum second factor count exceeded.',
    'auth/tenant-id-mismatch': 'Tenant ID mismatch.',
    'auth/timeout': 'The operation timed out. Please try again.',
    'auth/user-token-expired': 'User token has expired. Please sign in again.',
    'auth/too-many-requests': 'Too many requests. Please try again later.',
    'auth/unauthorized-continue-uri': 'Unauthorized continue URL.',
    'auth/unsupported-first-factor': 'Unsupported first factor.',
    'auth/unsupported-persistence-type': 'Unsupported persistence type.',
    'auth/unsupported-tenant-operation': 'Unsupported tenant operation.',
    'auth/unverified-email': 'Email is not verified.',
    'auth/user-cancelled': 'User canceled the operation.',
    'auth/user-not-found': 'No account found with this email.',
    'auth/user-disabled': 'This account has been disabled. Please contact support.',
    'auth/user-mismatch': 'User mismatch. Please try again.',
    'auth/user-signed-out': 'User is signed out.',
    'auth/weak-password': 'The password is too weak.',
    'auth/web-storage-unsupported': 'Web storage is unsupported on this browser.',
    'auth/already-initialized': 'Firebase is already initialized.',
    'auth/recaptcha-not-enabled': 'reCAPTCHA is not enabled.',
    'auth/missing-recaptcha-token': 'reCAPTCHA token is missing.',
    'auth/invalid-recaptcha-token': 'Invalid reCAPTCHA token.',
    'auth/invalid-recaptcha-action': 'Invalid reCAPTCHA action.',
    'auth/missing-client-type': 'Client type is missing.',
    'auth/missing-recaptcha-version': 'reCAPTCHA version is missing.',
    'auth/invalid-recaptcha-version': 'Invalid reCAPTCHA version.',
    'auth/invalid-req-type': 'Invalid request type.'
  };

  const code = error?.code ? (error.code.startsWith('auth/') ? error.code : `auth/${error.code}`) : 'auth/unknown';
  return errorMessages[code] || error.message || 'An unexpected error occurred.';
}
